vim.cmd('filetype plugin indent on')
vim.g.nord_italic = false
vim.g.nord_borders = true
--vim.g.nord_bold = false
vim.o.shortmess = vim.o.shortmess .. 'c' -- prevent "pattern not found" messages
--vim.o.hidden = true
vim.o.pumheight = 10 -- autocompletion height
vim.o.whichwrap = 'h,l' -- set wrap for these keys
vim.o.fileencoding = 'utf-8' -- the encoding written to a file
vim.o.splitbelow = true -- force all horizontal splits to go below current window
vim.o.splitright = true -- force all vertical splits to go to the right of current window
vim.o.termguicolors = true
vim.o.conceallevel = 0 -- prevent conceal
vim.o.showmode = false -- disable showmode message
vim.o.backup = false -- prevent create backup file
vim.o.writebackup = false -- disable to write backup file
vim.o.swapfile = false -- enable/disable swap file creation
vim.o.updatetime = 300 -- faster completion 
vim.o.timeoutlen = 2000 -- time to wait for a mapped sequence to complete ()
vim.o.clipboard = "unnamedplus" -- allows neovim to access the system clipboard
vim.o.hlsearch = true -- highlight all matches on previous search pattern
vim.o.ignorecase = true -- ignore case in search patterns
vim.o.scrolloff = 3 -- Minimal number of screen lines to keep above and below the cursor
vim.o.sidescrolloff = 5 -- The minimal number of columns to scroll horizontally
vim.o.mouse = "a" -- allow mouse in vim
vim.o.wrap = true -- enable wrap text
vim.o.number = true -- set number line
vim.o.relativenumber = true -- set relative number line
vim.o.cursorline = true -- set hightlight cursor line
vim.o.smartcase = true -- smart case when search text
--vim.o.signcolumn = "yes"
vim.o.tabstop = 2 -- how many columns a tab counts for
vim.o.shiftwidth = 2 -- the number of spaces inserted for each indentation
vim.o.smartindent = true -- make indenting smarter again
vim.o.expandtab = true -- convert tabs to spaces
vim.o.foldlevelstart = 99 -- stop autofolding when file open
vim.o.foldmethod = "indent" -- set default to indent
--vim.opt.wildmenu = true -- turn on command line completion wild style
--vim.opt.wildmode = "full"
--vim.opt.wildoptions = "pum"
--vim.o.wildignorecase = true -- When set case is ignored when completing file names and directories
