format = """$directory$git_branch$git_status$character"""

# Inserts a blank line between shell prompts
add_newline = false

[character] # The name of the module we are configuring is 'character'
success_symbol = '[➔ ](white)'
error_symbol =  '[➔ ](white)'
vimcmd_symbol =  '[➔ ](white)'

[cmd_duration]
disabled = true

[username]
disabled = true

[git_branch]
style = 'yellow'

[git_status]
style = 'yellow'
