require('plugins')
require('options')
require('nvim-tree-config')
require('lualine-config')
require('keymapping')
require('treesitter-config')
require('autopairs-config')
require('telescope-config')
require('lsp')
require('impatient-config')
require('gitsigns-config')
require('blankline-config')
require('comment-config')
require('surround-config')
vim.cmd('colorscheme nord')
